spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/adminapp
    username: cleanbrain
    password: cleanbrain!1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
